name: "Clemens Alexandrinus GPT"
slug: "clement"
languages: ["el", "lv", "en"]
domains: ["patristics", "greek-philology", "ancient-languages", "biblical-languages", "nt-greek-koine", "ot-hebrew"]
dataset:
  type: "external"
notes: "AL & BL Readings"
