name: Snapshot backup

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make snapshot
        run: |
          set -e
          TS=$(date -u +"%Y-%m-%d_%H-%M-%S")
          SNAP="snapshots/$TS"
          mkdir -p "$SNAP"
          # Saglabājam to, kas ietekmē dashboard
          cp -r docs "$SNAP/docs"
          if [ -f gpts.csv ]; then cp gpts.csv "$SNAP/gpts.csv"; fi
          if [ -d gpts ]; then cp -r gpts "$SNAP/gpts"; fi
          echo "SNAPSHOT=$SNAP" >> $GITHUB_ENV

      - name: Commit snapshot
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A snapshots
          if git diff --cached --quiet; then
            echo "Nothing to snapshot."
          else
            git commit -m "Snapshot: ${SNAPSHOT} [skip ci]"
            git push
          fi
