name: Build public API (api.json)
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "docs/index.json"
      - "docs/terms.json"
      - "docs/articles.json"
      - "scripts/build_api.py"
permissions:
  contents: write
jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Build api.json
        run: python scripts/build_api.py
      - name: Commit docs/api.json if changed
        run: |
          if ! git diff --quiet -- docs/api.json; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/api.json
            git commit -m "Build api.json [skip ci]"
            git push
          else
            echo "No changes."
          fi
