name: Build search indexes

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - gpts/**
      - gpts.csv
      - scripts/build_index.py
      - docs/index.html

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Build indexes
        run: |
          python scripts/build_index.py
      - name: Commit docs/*.json if changed
        run: |
          if ! git diff --quiet -- docs/index.json docs/terms.json docs/articles.json; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/index.json docs/terms.json docs/articles.json
            git commit -m "Build search indexes [skip ci]"
            git push
          else
            echo "No changes"
          fi
