name: List Files
on:
  workflow_dispatch:
jobs:
  list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show tree
        run: |
          sudo apt-get update >/dev/null 2>&1 || true
          sudo apt-get install -y tree >/dev/null 2>&1 || true
          echo "== Pilns failu koks =="
          tree -a -L 6
